services:
  - type: web
    name: lessence-placeorder-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: your_mongodb_connection_string
      - key: JWT_SECRET
        value: your_jwt_secret_key
      - key: PORT
        value: 3000